import { NextRequest, NextResponse } from 'next/server';
import ExcelJS from 'exceljs';

export async function POST(request: NextRequest) {
  try {
    const role = request.headers.get('x-user-role');
    if (role !== 'DIRECTOR') {
      return NextResponse.json(
        { error: 'Access denied. Director role required.', code: 'FORBIDDEN' },
        { status: 403 }
      );
    }

    const { title, headers, rows, format } = await request.json();

    if (!headers || !rows || !title) {
      return NextResponse.json({ error: 'Missing required report fields.' }, { status: 400 });
    }

    if (format === 'excel') {
      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet(title.slice(0, 31)); // Sheet name limit: 31 chars

      // Setup columns and header styling
      worksheet.columns = headers.map((h: string) => ({ header: h, key: h, width: 22 }));

      const headerRow = worksheet.getRow(1);
      headerRow.font = { name: 'Arial', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
      headerRow.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF241F6B' } // Brand primary navy
      };
      headerRow.alignment = { vertical: 'middle', horizontal: 'center' };
      headerRow.height = 25;

      // Populate data rows
      rows.forEach((rowData: any[]) => {
        const parsedRow = rowData.map(val => {
          // Convert strings representing numbers to real numbers for neat Excel calculation
          if (typeof val === 'string' && !isNaN(Number(val)) && val.trim() !== '') {
            return Number(val);
          }
          return val;
        });
        worksheet.addRow(parsedRow);
      });

      // Style alternating rows
      worksheet.eachRow((row, rowNumber) => {
        if (rowNumber === 1) return;
        row.height = 20;
        row.alignment = { vertical: 'middle' };
        if (rowNumber % 2 === 0) {
          row.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFF5F5F9' } // alternating row styling
          };
        }
        row.eachCell(cell => {
          cell.border = {
            top: { style: 'thin', color: { argb: 'FFE6E4F2' } },
            left: { style: 'thin', color: { argb: 'FFE6E4F2' } },
            bottom: { style: 'thin', color: { argb: 'FFE6E4F2' } },
            right: { style: 'thin', color: { argb: 'FFE6E4F2' } }
          };
        });
      });

      // Stream spreadsheet directly to browser
      const buffer = await workbook.xlsx.writeBuffer();
      
      return new Response(buffer, {
        headers: {
          'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'Content-Disposition': `attachment; filename="${title.replace(/[^a-zA-Z0-9]/g, '_')}.xlsx"`,
          'Access-Control-Expose-Headers': 'Content-Disposition'
        }
      });
    }

    if (format === 'pdf') {
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #26263a; margin: 0; }
            h1 { font-size: 18px; color: #241f6b; border-bottom: 2px solid #e6e4f2; padding-bottom: 12px; margin-bottom: 24px; text-transform: uppercase; letter-spacing: 0.5px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 11px; }
            th { background-color: #241f6b; color: white; text-align: left; padding: 10px; font-weight: bold; border: 1px solid #241f6b; }
            td { padding: 9px; border: 1px solid #e6e4f2; }
            tr:nth-child(even) td { background-color: #fcfaf5; }
            .footer { margin-top: 30px; font-size: 9px; color: #71708c; text-align: right; border-top: 1px solid #e6e4f2; padding-top: 8px; }
            @media print {
              .no-print { display: none; }
              body { padding: 20px; }
            }
          </style>
        </head>
        <body>
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;" class="no-print">
            <span style="font-size: 11px; color: #71708c;">Printable Document generated by MGE AI Manager</span>
            <button onclick="window.print()" style="background-color: #241f6b; color: white; border: none; padding: 6px 12px; border-radius: 4px; font-size: 11px; cursor: pointer; font-weight: bold;">Print / Save as PDF</button>
          </div>
          <h1>${title}</h1>
          <table>
            <thead>
              <tr>
                ${headers.map((h: string) => `<th>${h}</th>`).join('')}
              </tr>
            </thead>
            <tbody>
              ${rows.map((row: any[]) => `
                <tr>
                  ${row.map(val => `<td>${val === null || val === undefined ? 'N/A' : val}</td>`).join('')}
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="footer">
            Generated on ${new Date().toLocaleDateString('en-IN')} ${new Date().toLocaleTimeString('en-IN')} | Authorized by MGE Director.
          </div>
          <script>
            setTimeout(() => { window.print(); }, 500);
          </script>
        </body>
        </html>
      `;

      return new Response(htmlContent, {
        headers: {
          'Content-Type': 'text/html; charset=utf-8'
        }
      });
    }

    return NextResponse.json({ error: 'Unsupported export format.' }, { status: 400 });

  } catch (error) {
    console.error('[AI_MANAGER_EXPORT] Export compilation failed:', error);
    return NextResponse.json({ error: 'Failed to compile file export.' }, { status: 500 });
  }
}
